# Generated by Django 4.0 on 2023-10-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserNumero', models.IntegerField()),
                ('UserUrdideira', models.IntegerField()),
                ('UserOperador', models.CharField(max_length=40)),
                ('UserProduto', models.CharField(max_length=500)),
                ('UserFornecedor', models.CharField(max_length=500)),
                ('UserFio', models.IntegerField()),
                ('UserCorFio', models.CharField(max_length=500)),
                ('UserBob', models.IntegerField(blank=True)),
                ('UserQtdFio', models.IntegerField()),
                ('UserMaquina', models.IntegerField()),
                ('UserBarra', models.CharField(max_length=7)),
                ('UserRolos', models.IntegerField()),
                ('UserMetros', models.IntegerField()),
                ('UserData_cadastro', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
