# Generated by Django 4.0 on 2023-07-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_alter_user_useremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UserData_nascimento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserEmail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserNome',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserSobrenome',
        ),
        migrations.AddField(
            model_name='user',
            name='UserBob',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='UserCorFio',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='UserFio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='UserFornecedor',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='UserMaquina',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='UserMetros',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='UserNumero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='UserOperador',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='UserProduto',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='UserQtdFio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='UserRolos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='UserUrdideira',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
