# Generated by Django 4.0 on 2023-07-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_remove_user_userdata_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserQuebra',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
