# Generated by Django 4.0 on 2023-08-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_user_userquebra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UserQuebra',
        ),
        migrations.AddField(
            model_name='user',
            name='UserBarra',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserBob',
            field=models.IntegerField(blank=True),
        ),
    ]
