# Generated by Django 4.0 on 2023-07-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_user_userquebra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserQuebra',
            new_name='UserBarra',
        ),
    ]
