# Generated by Django 4.0 on 2023-07-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_rename_userquebra_user_userbarra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserBarra',
            field=models.CharField(max_length=6),
        ),
    ]
