# Generated by Django 4.0 on 2023-07-31 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_alter_user_userbarra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserBarra',
            new_name='Barra',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserBob',
            new_name='Bob',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserCorFio',
            new_name='CorFio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserData_cadastro',
            new_name='Data_cadastro',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserFio',
            new_name='Fio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserFornecedor',
            new_name='Fornecedor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserId',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserMaquina',
            new_name='Maquina',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserMetros',
            new_name='Metros',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserNumero',
            new_name='Numero',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserOperador',
            new_name='Operador',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserProduto',
            new_name='Produto',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserQtdFio',
            new_name='QtdFio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserRolos',
            new_name='Rolos',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserUrdideira',
            new_name='Urdideira',
        ),
    ]
