# Generated by Django 4.0 on 2023-07-31 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0010_rename_userbarra_user_barra_rename_userbob_user_bob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Barra',
            new_name='UserBarra',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Bob',
            new_name='UserBob',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='CorFio',
            new_name='UserCorFio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Data_cadastro',
            new_name='UserData_cadastro',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Fio',
            new_name='UserFio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Fornecedor',
            new_name='UserFornecedor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Id',
            new_name='UserId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Maquina',
            new_name='UserMaquina',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Metros',
            new_name='UserMetros',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Numero',
            new_name='UserNumero',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Operador',
            new_name='UserOperador',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Produto',
            new_name='UserProduto',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='QtdFio',
            new_name='UserQtdFio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Rolos',
            new_name='UserRolos',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Urdideira',
            new_name='UserUrdideira',
        ),
    ]
