# Generated by Django 4.0 on 2023-07-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0011_rename_barra_user_userbarra_rename_bob_user_userbob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserBob',
            field=models.IntegerField(blank=True),
        ),
    ]
