# Generated by Django 4.0 on 2023-07-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0012_alter_user_userbob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserBarra',
            field=models.CharField(max_length=7),
        ),
    ]
